GET http://localhost:7000/api/hello/hi
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImZmODFhODhmMzUxNmJkNmI1ZjhlMjg2YzY0MzgwYTlhIiwidHlwIjoiSldUIn0.eyJuYmYiOjE1NTYxOTA1NTAsImV4cCI6MTU1NjE5NDE1MCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NTAwMC9yZXNvdXJjZXMiLCJjdXN0b21BUEkiXSwiY2xpZW50X2lkIjoib2F1dGhDbGllbnQiLCJzY29wZSI6WyJjdXN0b21BUEkucmVhZCJdfQ.lq7PFYLkoZRAYbr9XYdCK-J3srJccYU-LX5zgpLl0qy-hH8uCbI7L3PlcB_akRpifC9HCM6POKha4mz9UWM-Ti0en40gvdTZgjvb9bsEb6vNr1T6TL-9yin6D9yCskiBMKmECe3540zdVJzhXaai-iJyK5HbXiPfDSsShW79-4KaZ7B0lCRTlM9p32AbOnlzvyZZowpE5L654B_LBCvvuNoh_4SqcbjOCMLZvDVHnvBtG3KpyLw-1BjggXcLFotfxg6aKXqZTH3kGGsy2KN5WQ7hda4qE_SeXL5iDk886c4UUGql7CxieTsbAlNccWd0woj5hL9Zk-qWy5higdxKkw
