GET http://localhost:5000/api/hello/hi
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImZmODFhODhmMzUxNmJkNmI1ZjhlMjg2YzY0MzgwYTlhIiwidHlwIjoiSldUIn0.eyJuYmYiOjE1NTYxOTEwMjMsImV4cCI6MTU1NjE5NDYyMywiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NTAwMC9yZXNvdXJjZXMiLCJjdXN0b21BUEkiXSwiY2xpZW50X2lkIjoib2F1dGhDbGllbnQiLCJzdWIiOiI1QkU4NjM1OS0wNzNDLTQzNEItQUQyRC1BMzkzMjIyMkRBQkUiLCJhdXRoX3RpbWUiOjE1NTYxOTEwMjMsImlkcCI6ImxvY2FsIiwicm9sZSI6ImFkbWluIiwic2NvcGUiOlsiY3VzdG9tQVBJLnJlYWQiXSwiYW1yIjpbInB3ZCJdfQ.UTfl5QNgaJfqiB-Uv4QRDbIEHJZyabTYG65rnU3XlcSIFBUV92G803Qi76lEka2PyYh4-adRP1oc-9gSQAc5ABTPAsPJC2uDQAzWzdNTVyaBIItXToKpx7fji8S-zoWAWk1XFjcqK4Fehm_LG1g3hVTHZdzfAat7gsYa_nuUrBQ6tZb1cy0T0u9RYS4SED6FAOphGkApw0FZqmhC-82guWmMsybtRV_hoQkOQ0RHQ_E0Jd-IK4PlCjnyFFqo_f37_QAOpvXByAe6_ljEq2vQuX7s7SA6MIEHBCKR0FL70IxBkRHLYWbb1GRU1Cv-3CkX-_HpT17dcUqwos0GnhRHRw

### Go
GET http://localhost:5000/api/hello/hi
# Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImZmODFhODhmMzUxNmJkNmI1ZjhlMjg2YzY0MzgwYTlhIiwidHlwIjoiSldUIn0.eyJuYmYiOjE1NTYxODQ1MDEsImV4cCI6MTU1NjE4ODEwMSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NTAwMC9yZXNvdXJjZXMiLCJjdXN0b21BUEkiXSwiY2xpZW50X2lkIjoib2F1dGhDbGllbnQiLCJzY29wZSI6WyJjdXN0b21BUEkucmVhZCJdfQ.ONfAb-CwkBAb_kUelMDKNQLi0u65LvVetCL6yPAl8F6LWw1F_8zPjSfkQaDcioMBroyRANEQBcpVufTNIH46PSHoudl1Nqrt2dO-shU2WNS8ohCRyHwFfJR4NPZdGCFhIBlhJJUEw1RDTljnYfJvN_xVkSep6U6os4fLDvtfQMy6s8bQgWXyfPr7ceCRgBx8sPMimZ933jPIDzb2TNvmnXWN0cM3vNL3kzbU2XhLFYYnLkUIlOE5tFWTVBiD7QD-x54vf_U_alF9R0_hCxLwDF2UBZ2QUy-Ckn7EYRDA_j1o_bAau_qjBHiuUSRkHH_2yhbwCQc6SX1N0cs-ku92Vw

### Value
GET http://localhost:5000/api/values