GET http://localhost:5000/api/hello/hi
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImZmODFhODhmMzUxNmJkNmI1ZjhlMjg2YzY0MzgwYTlhIiwidHlwIjoiSldUIn0.eyJuYmYiOjE1NTYxODgwNjMsImV4cCI6MTU1NjE5MTY2MywiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NTAwMC9yZXNvdXJjZXMiLCJjdXN0b21BUEkiXSwiY2xpZW50X2lkIjoib2F1dGhDbGllbnQiLCJzdWIiOiI1QkU4NjM1OS0wNzNDLTQzNEItQUQyRC1BMzkzMjIyMkRBQkUiLCJhdXRoX3RpbWUiOjE1NTYxODgwNjMsImlkcCI6ImxvY2FsIiwicm9sZSI6ImFkbWluIiwic2NvcGUiOlsiY3VzdG9tQVBJLnJlYWQiXSwiYW1yIjpbInB3ZCJdfQ.areVBr5ZvXTLJUiT6H-h6QYfSR_XqHJbKmc-VCIRRo-gFAYOAE0UA36Ztq4YQzqGCypBIdawdIvNiDfxYI2LcQCknvoWYrOnECapPKwo0e3UUutTQyV61OPkcNIFICsSw4u-bkM6_8CZoryfjHa-frNUpXUNkOf8XEi3YwZy7Qf6HMN89uyfzn8MEM9Vx82rF29R6oO52ZD0JuVVLHYIaOtcCbx9GCNOlSOhP-MKL74CFjkfwCuku8HyHRxNYCKZgPQH3EbTht779LpRsBoYNVsxIsPELzarUeXJ0VbR_nSRicp2m0SbAzgZH_GS7R4ddlVTdf5qWpfNlATyDAP1Kg

### Go
GET http://localhost:5000/api/hello/hi
# Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImZmODFhODhmMzUxNmJkNmI1ZjhlMjg2YzY0MzgwYTlhIiwidHlwIjoiSldUIn0.eyJuYmYiOjE1NTYxODQ1MDEsImV4cCI6MTU1NjE4ODEwMSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NTAwMC9yZXNvdXJjZXMiLCJjdXN0b21BUEkiXSwiY2xpZW50X2lkIjoib2F1dGhDbGllbnQiLCJzY29wZSI6WyJjdXN0b21BUEkucmVhZCJdfQ.ONfAb-CwkBAb_kUelMDKNQLi0u65LvVetCL6yPAl8F6LWw1F_8zPjSfkQaDcioMBroyRANEQBcpVufTNIH46PSHoudl1Nqrt2dO-shU2WNS8ohCRyHwFfJR4NPZdGCFhIBlhJJUEw1RDTljnYfJvN_xVkSep6U6os4fLDvtfQMy6s8bQgWXyfPr7ceCRgBx8sPMimZ933jPIDzb2TNvmnXWN0cM3vNL3kzbU2XhLFYYnLkUIlOE5tFWTVBiD7QD-x54vf_U_alF9R0_hCxLwDF2UBZ2QUy-Ckn7EYRDA_j1o_bAau_qjBHiuUSRkHH_2yhbwCQc6SX1N0cs-ku92Vw

### Value
GET http://localhost:5000/api/values