POST http://localhost:5000/connect/introspect
Content-Type: application/x-www-form-urlencoded
# Authorization: Basic Y3VzdG9tQVBJOnNjb3BlU2VjcmV0
Authorization: Basic customAPI scopeSecret


token=eyJhbGciOiJSUzI1NiIsImtpZCI6ImZmODFhODhmMzUxNmJkNmI1ZjhlMjg2YzY0MzgwYTlhIiwidHlwIjoiSldUIn0.eyJuYmYiOjE1NTYxODQ1MDEsImV4cCI6MTU1NjE4ODEwMSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NTAwMC9yZXNvdXJjZXMiLCJjdXN0b21BUEkiXSwiY2xpZW50X2lkIjoib2F1dGhDbGllbnQiLCJzY29wZSI6WyJjdXN0b21BUEkucmVhZCJdfQ.ONfAb-CwkBAb_kUelMDKNQLi0u65LvVetCL6yPAl8F6LWw1F_8zPjSfkQaDcioMBroyRANEQBcpVufTNIH46PSHoudl1Nqrt2dO-shU2WNS8ohCRyHwFfJR4NPZdGCFhIBlhJJUEw1RDTljnYfJvN_xVkSep6U6os4fLDvtfQMy6s8bQgWXyfPr7ceCRgBx8sPMimZ933jPIDzb2TNvmnXWN0cM3vNL3kzbU2XhLFYYnLkUIlOE5tFWTVBiD7QD-x54vf_U_alF9R0_hCxLwDF2UBZ2QUy-Ckn7EYRDA_j1o_bAau_qjBHiuUSRkHH_2yhbwCQc6SX1N0cs-ku92Vw